### ISSUE TITLE
Dont work ...

### ISSUE THREAD

**Issue by unclesamwk** [Lunik/amon-docker#2]
Hey,

i started the container with https support, but nothing work.

```Attaching to amon-docker_amon_1
amon_1   | nginx: [emerg] BIO_new_file("/etc/opt/amon/ssl/mondomain.exemple.crt") failed (SSL: error:02FFF002:system library:func(4095):No such file or directory:fopen('/etc/opt/amon/ssl/mondomain.exemple.crt', 'r') error:20FFF080:BIO routines:CRYPTO_internal:no such file)
amon_1   | Operations to perform:
amon_1   |   Apply all migrations: auth, contenttypes, sessions, users
amon_1   | Running migrations:
amon_1   |   Applying contenttypes.0001_initial... OK
amon_1   |   Applying contenttypes.0002_remove_content_type_name... OK
amon_1   |   Applying auth.0001_initial... OK
amon_1   |   Applying auth.0002_alter_permission_name_max_length... OK
amon_1   |   Applying auth.0003_alter_user_email_max_length... OK
amon_1   |   Applying auth.0004_alter_user_username_opts... OK
amon_1   |   Applying auth.0005_alter_user_last_login_null... OK
amon_1   |   Applying auth.0006_require_contenttypes_0002... OK
amon_1   |   Applying auth.0007_alter_validators_add_error_messages... OK
amon_1   |   Applying auth.0008_alter_user_username_max_length... OK
amon_1   |   Applying auth.0009_alter_user_last_name_max_length... OK
amon_1   |   Applying sessions.0001_initial... OK
amon_1   |   Applying users.0001_initial... OK
amon_1   | 3 tasks installed.
amon_1   | [2018-08-10 12:31:05 +0000] [1] [INFO] Starting gunicorn 19.6.0
amon_1   | [2018-08-10 12:31:05 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
amon_1   | [2018-08-10 12:31:05 +0000] [1] [INFO] Using worker: gevent
amon_1   | [2018-08-10 12:31:05 +0000] [158] [INFO] Booting worker with pid: 158
amon_1   | [2018-08-10 12:31:05 +0000] [159] [INFO] Booting worker with pid: 159
amon_1   | [2018-08-10 12:31:05 +0000] [160] [INFO] Booting worker with pid: 160
amon_1   | [2018-08-10 12:31:05 +0000] [161] [INFO] Booting worker with pid: 161
amon_1   | [2018-08-10 12:32:23 +0000] [1] [INFO] Handling signal: term
amon_1   | nginx: [emerg] BIO_new_file("/etc/opt/amon/ssl/mondomain.exemple.crt") failed (SSL: error:02FFF002:system library:func(4095):No such file or directory:fopen('/etc/opt/amon/ssl/mondomain.exemple.crt', 'r') error:20FFF080:BIO routines:CRYPTO_internal:no such file)
amon_1   | Operations to perform:
amon_1   |   Apply all migrations: auth, contenttypes, sessions, users
amon_1   | Running migrations:
amon_1   |   No migrations to apply.
amon_1   | 3 tasks removed, 3 installed.
amon_1   | [2018-08-10 12:32:34 +0000] [1] [INFO] Starting gunicorn 19.6.0
amon_1   | [2018-08-10 12:32:34 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
amon_1   | [2018-08-10 12:32:34 +0000] [1] [INFO] Using worker: gevent
amon_1   | [2018-08-10 12:32:34 +0000] [157] [INFO] Booting worker with pid: 157
amon_1   | [2018-08-10 12:32:34 +0000] [158] [INFO] Booting worker with pid: 158
amon_1   | [2018-08-10 12:32:34 +0000] [159] [INFO] Booting worker with pid: 159
amon_1   | [2018-08-10 12:32:34 +0000] [160] [INFO] Booting worker with pid: 160```

I think it was easier to use traefik as http proxy.
There was lets encrypt support with renew all certificates and so on.

greetings
Sam

**Comment by unclesamwk** [comment]
I change port in docker compose to "80:8000" then i can open amon in browser.

ERROR
```
Forbidden (403)
CSRF verification failed. Request aborted.

You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.

If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for 'same-origin' requests.

More information is available with DEBUG=True.
```

**Comment by unclesamwk** [comment]
i check if nginx is running in container, it dont because .

```nginx: [emerg] BIO_new_file("/etc/opt/amon/ssl/mondomain.exemple.crt") failed (SSL: error:02FFF002:system library:func(4095):No such file or directory:fopen('/etc/opt/amon/ssl/mondomain.exemple.crt', 'r') error:20FFF080:BIO routines:CRYPTO_internal:no such file)```

**Comment by unclesamwk** [comment]
```
version: '2'
services:
  traefik:
    restart: always
    image: traefik:1.6
    container_name: traefik
    command: --web --docker --logLevel=DEBUG
    labels:
      - "traefik.frontend.rule=Host:docker.lan"
      - "traefik.port=8080"
      - "traefikLogsFile=/logs/traefik.log"
      - "accessLogsFile=/logs/access.log"
    ports:
      - "80:80"
      - "8888:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefikdata/traefik.toml:/traefik.toml
    networks:
      - webgateway

  amon:
    build: "./image"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - AMON_PROTO=https
      - AMON_HOSTNAME=amon.example.de
    volumes:
      - "./amon:/etc/opt/amon/"
      - "./log:/var/log/amon/"
    networks:
      - webgateway
    labels:
      traefik.port: "443"
      traefik.enable: "true"
      traefik.docker.network: "traefik"
      traefik.frontend.rule: "Host:amon.example.de"

  mongo:
    image: "mongo:latest"
    command: --smallfiles
    volumes:
      - ./db:/data/db
    networks:
      - webgateway


networks:
  webgateway:
    driver: bridge
```
